### ISSUE TITLE
Uncaught exception 'Masih\\YoutubeDownloader\\YoutubeException' with message 'exception 'V8JsException' with message 'base.js:7625

### ISSUE THREAD

**Issue by jianub** [masihyeganeh/YoutubeDownloader#13]
I get the following error. This is my V8js config :

 V8 Javascript Engine	enabled
V8 Engine Compiled Version	3.14.5.8
V8 Engine Linked Version	3.14.5.8
Version	0.1.3

[Tue Jan 03 16:25:37.090572 2017] [:error] [pid 2255] [client 188.25.186.45:52902] PHP Fatal error:  Uncaught exception 'Masih\\YoutubeDownloader\\YoutubeException' with message 'exception 'V8JsException' with message 'base.js:7625: TypeError: Object #<Masih\\YoutubeDownloader\\WindowStub> has no method '$signature'' in /var/www/www-root/data/www/youtubeable.net/download2/Masih/YoutubeDownloader/YoutubeDownloader.php:339\nStack trace:\n#0 /var/www/www-root/data/www/youtubeable.net/download2/Masih/YoutubeDownloader/YoutubeDownloader.php(339): V8Js->executeString('var _yt_player=...', 'base.js')\n#1 /var/www/www-root/data/www/youtubeable.net/download2/Masih/YoutubeDownloader/YoutubeDownloader.php(459): Masih\\YoutubeDownloader\\YoutubeDownloader->decryptSignature('E2FA18845FA379D...', 'var _yt_player=...')\n#2 /var/www/www-root/data/www/youtubeable.net/download2/Masih/YoutubeDownloader/YoutubeDownloader.php(528): Masih\\YoutubeDownloader\\YoutubeDownloader->getVideoInfo()\n#3 /var/www/www-root/data/www/youtubeable.net/download2/index.php(9): Masih\\YoutubeDownloader\\YoutubeDownloader->getInfo()\n#4 {main}' in /var/www/www-ro in /var/www/www-root/data/www/youtubeable.net/download2/Masih/YoutubeDownloader/YoutubeDownloader.php on line 341

**Comment by masihyeganeh** [comment]
Please give me the video ID so I can inspect it. It is not because of V8Js.
Your setup is ok

On Jan 4, 2017 12:55 AM, "jianub" <notifications@github.com> wrote:

I get the following error. This is my V8js config :

V8 Javascript Engine enabled
V8 Engine Compiled Version 3.14.5.8
V8 Engine Linked Version 3.14.5.8
Version 0.1.3

[Tue Jan 03 16:25:37.090572 2017] [:error] [pid 2255] [client
188.25.186.45:52902] PHP Fatal error: Uncaught exception
'Masih\YoutubeDownloader\YoutubeException' with message 'exception
'V8JsException' with message 'base.js:7625: TypeError: Object
#<Masih\YoutubeDownloader\WindowStub> has no method '$signature'' in
/var/www/www-root/data/www/youtubeable.net/download2/Masih/
YoutubeDownloader/YoutubeDownloader.php:339\nStack
<http://youtubeable.net/download2/Masih/YoutubeDownloader/YoutubeDownloader.php:339%5CnStack>
trace:\n#0 /var/www/www-root/data/www/youtubeable.net/download2/Masih/
YoutubeDownloader/YoutubeDownloader.php(339): V8Js->executeString('var
_yt_player=...', 'base.js')\n#1 /var/www/www-root/data/www/you
tubeable.net/download2/Masih/YoutubeDownloader/YoutubeDownloader.php(459):
Masih\YoutubeDownloader\YoutubeDownloader->decryptSignature('E2FA18845FA379D...',
'var _yt_player=...')\n#2 /var/www/www-root/data/www/you
tubeable.net/download2/Masih/YoutubeDownloader/YoutubeDownloader.php(528):
Masih\YoutubeDownloader\YoutubeDownloader->getVideoInfo()\n#3
/var/www/www-root/data/www/youtubeable.net/download2/index.php(9):
Masih\YoutubeDownloader\YoutubeDownloader->getInfo()\n#4 {main}' in
/var/www/www-ro in /var/www/www-root/data/www/you
tubeable.net/download2/Masih/YoutubeDownloader/YoutubeDownloader.php on
line 341

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/masihyeganeh/YoutubeDownloader/issues/13>, or mute the
thread

**Comment by jianub** [comment]
9u7hGkL57N8 is the videoid

**Comment by masihyeganeh** [comment]
Thanks for reporting. Will fix it today and release a new version.

**Comment by masihyeganeh** [comment]
This bug has been fixed in previous versions and will definitely work in the new 2.9.0 version. test it if you want
