### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by mailightkun** [masihyeganeh/YoutubeDownloader#19]
I tried this url: http://www.youtube.com/watch?v=9u7hGkL57N8
but i doesn't show any informations.. 

and your exceptions response was 'Could not get video page content'

**Comment by mailightkun** [comment]
and also, how can i download the file without saving it in my server?.. just download it.. right away once the user get the information details?

**Comment by masihyeganeh** [comment]
Hello.
Please download latest version and if after that the problem persists, it maybe because VEVO is not available in all countries. try it with a VPN or proxy. I could download it btw.

if you want to just get the link, you should just call `getInfo` method with `true` as it's first parameter. Then it will give you all information about the video including download links:

```php
<?php
include 'vendor/autoload.php';
use \Masih\YoutubeDownloader\YoutubeDownloader;

$youtube = new YoutubeDownloader('9u7hGkL57N8');
$info = $youtube->getInfo(true);
print_r($info);
```
